// generated by copilot for testing the number.go file
package tests

import (
	"testing"
	"year2024/internal/utils"
)

// Generic helper function to test numbers
func assertNumber[T utils.Number](t *testing.T, value T, expected T) {
	if value != expected {
		t.Errorf("Expected %v to be %v, got %v", value, expected, value)
	}
}

// Test function using the generic helper
func TestNumber(t *testing.T) {
	// Integers
	assertNumber(t, int(10), 10)
	assertNumber(t, int8(10), int8(10))
	assertNumber(t, int16(10), int16(10))
	assertNumber(t, int32(10), int32(10))
	assertNumber(t, int64(10), int64(10))

	// Unsigned Integers
	assertNumber(t, uint(10), uint(10))
	assertNumber(t, uint8(10), uint8(10))
	assertNumber(t, uint16(10), uint16(10))
	assertNumber(t, uint32(10), uint32(10))
	assertNumber(t, uint64(10), uint64(10))

	// Floating Points
	assertNumber(t, float32(10.0), float32(10.0))
	assertNumber(t, float64(10.0), float64(10.0))
}
