// generated by copilot for testing tomMath.go file
package tests

import (
	"testing"
	"year2024/internal/utils"
)

func TestAbsDiff(t *testing.T) {
	tests := []struct {
		name     string
		a, b     int
		expected int
	}{
		{"positive numbers", 5, 3, 2},
		{"negative numbers", -5, -3, 2},
		{"mixed numbers", 5, -3, 8},
		{"zero difference", 5, 5, 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := utils.AbsDiff(tt.a, tt.b)
			if result != tt.expected {
				t.Errorf("AbsDiff(%d, %d) = %d; want %d", tt.a, tt.b, result, tt.expected)
			}
		})
	}
}
